name: PR Comment Triggers
on:
  issue_comment:
    types: [created, edited]

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cirrus-actions/rebase@1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  revert_commit:
    name: Revert commit
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/revert')
    steps:
      - uses: actions/checkout@v2
      - uses: srt32/revert@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
