name: Auto Comment
on: [pull_request]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: jungwinter/comment@v1
        id: create
        with:
          type: create
          body: "- [ ] Run tests"
          issue_number: ${{ github.event.pull_request.id }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update comment
        uses: jungwinter/comment@v1
        with:
          type: edit
          body: "- [x] Run tests"
          comment_id: ${{ steps.create.outputs.id }}
          token: ${{ secrets.GITHUB_TOKEN }}
