name: Taichi Per-submit Check
on:
  push:
    branches:
      - master

jobs:
  update_commit_id:
    name: Update Commit Hash ID
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build Taichi
        run: |
          echo CC=$CC CXX=$CXX PYTHON_VERSION=$PYTHON_VERSION PYTHON=$PYTHON
        env:
          CC: clang
          CXX: clang++
          PYTHON_VERSION: 3.8.1
          PYTHON: python
      - name: Enforce code format
        run: |
          git rev-parse HEAD > commit_hash.txt
          git add .
          git config user.email "taichigardener@gmail.com"
          git config user.name "Taichi Gardener"
          git commit -m "[skip ci] enforce code format"
          git push
