name: Taichi Per-submit Check
on:
  push:
    branches:
      - master

jobs:
  update_commit_id:
    name: Update Commit Hash ID
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code
        run: |
          git rev-parse HEAD > hello.txt
          git add hello.txt
      - name: Push commit
        uses: taichi-dev/gardener@master
        with:
          args: "[skip ci] enforce code format"
