name: Review Requested Hooks
on:
  pull_request:
    types: [review_requested]

jobs:
  format:
    runs-on: ubuntu-latest
    #if: ${{ github.event.pull_request.review_requested.reviewer == 'taichi-gardener' }
    steps:
      - name: Trigger Format Server
        run: |
          echo ${{ github.event.pull_request.requested_reviewers }}
          echo ${{ contains(github.event.pull_request.requested_reviewers, 'taichi-gardener') }}
          echo curl http://kun.csail.mit.edu:31415/${{ github.event.pull_request.number }} -LO || :
