name: Test Action
on:
  pull_request:
    types: [opened, editied, synchronize, reopened]

jobs:
  check_title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          python check_pr_title.py $PR_TITLE
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
